site_name: /home/zenuo
site_url: https://zenuo.github.io/
theme:
  name: material
  font: false
  logo: assets/img/22318999.jpeg
  favicon: assets/img/22318999.jpeg
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github-square
repo_url: https://github.com/zenuo/zenuo.github.io
repo_name: zenuo/zenuo.github.io
extra:
  consent:
    title: Cookie consent
markdown_extensions:
  - tables
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed